### PR TITLE
Moved *.java files into new src directory

### PR DESCRIPTION
**Pull request by goelp14**
I followed your instructions to the best of my abilities. For the squash I used the command "git rebase -i HEAD~4". I'm not sure if that's what you meant by it but I have at least done everything else you asked for. I hope this works for you.

### CODE REVIEW

**Comment by shraiysh** [comment]
Hey! I am sorry that I've confused you a little... :smile:. Anyways, what I meant was for you to change the commit message with the command `git commit --amend` and add the line `Fixes #1` in it. You have currently changed the PR title. It was okay earlier. If you add this line to your commit message, GitHub will automatically link your PR and the issue.

**Comment by goelp14** [comment]
@shraiysh I used git commit --amend. The user @PGODULTIMATE is my account. For some reason it is showing as two separate accounts I do not know why. PGODULTIMATE is not supposed to be my username.

**Comment by drpeabody** [comment]
Hey @goelp14! I think you did not change the commit message as it still shows the same message. After running `git commit --amend`, it will prompt you for the new message and you are supposed to enter `Fixes #1` there.  I think this is what @shraiysh wants you to do. @shraiysh please confirm.

**Comment by goelp14** [comment]
@drpeabody I believe I did that. I ran `git commit --amend` and then saved it with `:wq` and then pushed it once more. The terminal said I succeeded.

**Comment by shraiysh** [comment]
I have updated the commit message and now, you can see that this pull request is linked to the issue. As soon as I expand the issue on GitHub, it will show me that this pull request references my issue. I'll merge this now. Hope you understood how that worked out.

**Pull request merged**
